baseurl = "//v0-16.choerodon.io/"
title = "Choerodon | 开源多云技术平台"
theme = "choerodon-document-theme"
# themesDir = "../.."
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir= "true"
prettyurls=true
# Define the number of posts per page
paginate = 5
# Open highlight
#pygmentsCodeFences = true

[languages]
    [languages.en]
        languageName = "English"
    [languages.zh]
        languageName = "中文"

[menu]
# Main menu
[[languages.en.menu.main]]
    name = "Docs"
    url  = "/en/docs/"
    weight = 1

[[languages.en.menu.main]]
    name = "Blog"
    url  = "/en/blog/"
    weight = 2

[[languages.en.menu.main]]
    name = "Case Studies"
    url  = "/en/case-studies/"
    weight = 3

[[languages.en.menu.main]]
    name = "Community"
    url  = "/en/community/"
    weight = 4
    identifier = "en-community"
    pre = "<i class='iconfont'>&#xe600;</i>"
    
    [[languages.en.menu.main]]
	        name = "Community"
	        url  = "/en/community/"
	        weight = 4
	        parent = "en-community"
	
	[[languages.en.menu.main]]
	        name = "Knowledge-Sharing"
	        url  = "/en/knowledge-sharing"
	        weight = 3
	        parent = "en-community" 


[[languages.en.menu.main]]
    name = "Github"
    url  = "https://github.com/choerodon/choerodon"
    weight = 5
    post= true

[[languages.en.menu.main]]
    name = "v0.16"
    url  = "/en/"
    weight = 6
    identifier = "version"
    pre = "<i class='iconfont'>&#xe600;</i>"

    [[languages.en.menu.main]]
        name = "v0.16"
        url  = "http://v0-16.choerodon.io/en/"
        weight = 6
        parent = "version"

    [[languages.en.menu.main]]
    name = "latest"
    url  = "http://choerodon.io/en/"
    weight = 5
    parent = "version"

[[languages.zh.menu.main]]
    name = "文档"
    url  = "/zh/docs/"
    weight = 1

[[languages.zh.menu.main]]
    name = "博客"
    url  = "/zh/blog/"
    weight = 2

[[languages.zh.menu.main]]
    name = "案例"
    url  = "/zh/case-studies/"
    weight = 3

[[languages.zh.menu.main]]
    name = "社区"
    url  = "/zh/community/"
    weight = 4
    identifier = "community"
    pre = "<i class='iconfont'>&#xe600;</i>"
    
	[[languages.zh.menu.main]]
	        name = "社区"
	        url  = "/zh/community/"
	        weight = 4
	        parent = "community"	
	[[languages.zh.menu.main]]
	        name = "知识分享"
	        url  = "/zh/knowledge-sharing"
	        weight = 3
	        parent = "community"        
	        
[[languages.zh.menu.main]]
    name = "GITHUB"
    url  = "https://github.com/choerodon/"
    weight = 5
    post= true
    identifier = "github"

[[languages.zh.menu.main]]
    name = "v0.16"
    url  = "/zh/"
    weight = 6
    identifier = "version"
    pre = "<i class='iconfont'>&#xe600;</i>"

    [[languages.zh.menu.main]]
        name = "v0.16"
        url  = "http://v0-16.choerodon.io/zh/"
        weight = 7
        parent = "version"
    [[languages.zh.menu.main]]
        name = "latest"
        url  = "http://choerodon.io/zh/"
        weight = 6
        parent = "version"

[params]
    viewMorePostLink = "/blog/"
    author = "Choerodon"
    tryhref = "https://organization.choerodon.com.cn/#/organization/register-organization"
    ajaxhref = "https://share.choerodon.com.cn/topic/apply"
    praisenumber ="https://share.choerodon.com.cn/video/query"
    defaultKeywords = ["devops"]
    defaultDescription = ""
    # Format dates with Go's time formatting
    date_format = "2006-01-02"
